### ISSUE TITLE
Kinematic bodies aren't moving

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/playcanvas-p2.js#1]
Setting the velocity either on the p2Body script initial settings or directly using p2Body.body.velocity doesn't have any effect.

Traced this as a bug on the ps2 integration script on line 195:
https://github.com/playcanvas/playcanvas-p2.js/blob/master/p2-integration.js#L195

Instead of:

`if (body.type === p2.Body.DYNAMIC) {`

I think it should be:

`if (body.type === p2.Body.DYNAMIC || body.type === p2.Body.KINEMATIC) {`

**Comment by willeastcott** [comment]
I think you may be right! 👍 

I have updated [the project on playcanvas.com](https://playcanvas.com/project/446127/overview/p2js-integration) to include a kinematic demo that shows this now works. Thanks!
