### ISSUE TITLE
Playcanvas p2 scripts are not available

### ISSUE THREAD

**Issue by christinakal** [playcanvas/playcanvas-p2.js#2]
I put the p2-interaction.js and p2.min.js in place in the PlayCanvas editor, but when parsing the script the following error appears in the console:
![image](https://user-images.githubusercontent.com/40663075/61631041-8dbd4800-ac89-11e9-935d-21fdd80e3af9.png)

and the scripts are not available to add on any entity.

**Comment by willeastcott** [comment]
This seems to be a bug in the Editor. I'll make sure this gets fixed. But in the meantime, to get the playcanvas-p2.js script to parse successfully, just delete the placeholder attribute from all scripts attribute definitions. 

For example, change:

```
P2World.attributes.add('gravity', { 
    type: 'vec2', 
    default: [ 0, -9.8 ],
    title: 'Gravity',
    description: 'Gravity to use when approximating the friction max force.',
    placeholder: ['X', 'Y']
});
```

To:

```
P2World.attributes.add('gravity', { 
    type: 'vec2', 
    default: [ 0, -9.8 ],
    title: 'Gravity',
    description: 'Gravity to use when approximating the friction max force.'
});
```

**Comment by christinakal** [comment]
Hm, unfortunately, it doesn't seem to work for me. When I parse the script, the attributes appear and after 2 sec disappear.

**Comment by willeastcott** [comment]
Well, there are several placeholder attributes to delete. You may have missed one. Here's the modified version I tested with:

https://playcanvas.com/editor/code/629413?tabs=21628669

**Comment by christinakal** [comment]
Yes, you're right, lost one. This fixed the issue. Thank you!

**Comment by mmmerl** [comment]
Hi @christinakal, we've pushed a fix to the editor that should resolve the issue with the placeholder attribute. Let me know if it is working for you.

**Comment by christinakal** [comment]
Yes, works great! Thank you guys!
